version: "3.8"

services:
  elasticmq:
    image: softwaremill/elasticmq
    ports:
      - "9324:9324"
  db:
    image: postgres:11.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
