SELECT 'CREATE DATABASE nockslots'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'nockslots')\gexec

\c nockslots;

CREATE TABLE IF NOT EXISTS public.messages (
     id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     body  json NOT NULL
);

INSERT INTO public.messages (body) VALUES ('{"first": "message", "for": "sanity"}');