SELECT 'CREATE DATABASE nockslots'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'nockslots')\gexec

\c nockslots;

CREATE TABLE IF NOT EXISTS public.messages (
     id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     body  json NOT NULL,
     encoded_message text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.processed_messages (
     id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     body  json NOT NULL,
     enriched_message text NOT NULL
);

INSERT INTO public.messages (body, encoded_message) VALUES ('{"first": "message", "for": "sanity"}', 'yes');