AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-ts-node-cron

Resources:
  MyCronFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-cron/
      Handler: app.handler
      Runtime: nodejs12.x
      Timeout: 300000
      Events:
        StartScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: cron(*/5 * * * ? *)
